export const Colors = {
  bgColor: "#F8F8F8",
  bgCard: "#EBEBEB",
  primary: "#6200EE",
  primaryLight: "#EFE6FD",
  primaryHover: "#CEB0FA",
  gray: "#151515",
  lightGray: "#949CA9",
  success: "#52C41A",
  warning: "#FAAD14",
  error: "#FF4D4F",
  white: "#FEFEFE",
  border: "#24272C",
  textGray: "#767676",
  textWarningHover: "#FCC862",
  textErrorHover: "#FF8889",
};

export const FontSizes = {
  headingLarge: "36px",
  headingLargeHeight: "45.18px",
  headingMedium: "16px",
  headingMediumHeight: "19.5px",
  headingSmall: "20px",
  headingSmalHeight: "25.1px",
  buttonSize: "16px",
  buttomSizeHeight: "20.08px",
  inputTitleSize: "14px",
  inputTitleSizeHeight: "16.8px",
  inputSize: "16px",
  inputSizeHeight: "19.2px",
  titleSize: "16px",
  titleSizeHeight: "19.5px",
  contentSize: "14px",
  contentSizeHeight: "21px",
  contentSmallSizes: "12px",
  contentSmallSizesHeight: "15px",
};
